"""empty message

Revision ID: 35a4594a1321
Revises: 8142db65de9e
Create Date: 2023-10-04 20:42:21.535731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a4594a1321'
down_revision = '8142db65de9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tracks_pkey')
    )
    # ### end Alembic commands ###
