"""empty message

Revision ID: 8142db65de9e
Revises: e79926d041c0
Create Date: 2023-10-04 20:40:03.207394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8142db65de9e'
down_revision = 'e79926d041c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint('tracks_record_id_fkey', type_='foreignkey')
        batch_op.drop_column('length')
        batch_op.drop_column('name')
        batch_op.drop_column('position')
        batch_op.drop_column('record_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('length', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tracks_record_id_fkey', 'records', ['record_id'], ['id'])

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
