"""empty message

Revision ID: bc5e3b3a25ff
Revises: e4fa3b64c405
Create Date: 2023-10-03 10:10:16.229204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5e3b3a25ff'
down_revision = 'e4fa3b64c405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('format', sa.String(), nullable=True))

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('length',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    with op.batch_alter_table('users_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_records', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('length',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('format')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
