"""add unique constraint to users_records

Revision ID: cda36c976751
Revises: 43882cb6cc3b
Create Date: 2024-07-24 14:03:18.168728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cda36c976751'
down_revision = '43882cb6cc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Records')
    with op.batch_alter_table('users_records', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_record', ['user_id', 'record_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_records', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_record', type_='unique')

    # ### end Alembic commands ###
