"""empty message

Revision ID: e4fa3b64c405
Revises: 4fc85331814c
Create Date: 2023-10-02 21:05:08.668703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4fa3b64c405'
down_revision = '4fc85331814c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('length',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('length',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###
